"""Publish a 'TRM runs overview' wandb Report driven by the wandb API.

Pulls every run in the configured project, formats summary metrics into a
markdown table + per-run sections, and saves the result as a wandb Report
visible at wandb.ai/<entity>/<project>/reports/<slug>. Re-running creates a
new version of the report — the latest is always at the top.

This is the live counterpart to findings.md's runs table: edit the source
markdown to add narrative, but use this Report for the always-current
metrics view.

Usage
-----
    python scripts/publish_runs_overview_report.py
    python scripts/publish_runs_overview_report.py --project TRM --top-n 30
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from dotenv import load_dotenv  # noqa: E402

load_dotenv(REPO_ROOT / ".env")

import wandb  # noqa: E402
import wandb_workspaces.reports.v2 as wr  # noqa: E402
from wandb_workspaces.reports.v2.interface import _get_api  # noqa: E402

# Same tolerant-create-project shim as publish_wandb_metrics_report.py — see
# that file for the explanation.
_api_class = _get_api().__class__
_orig_create_project = _api_class.create_project


def _tolerant_create_project(self, project, entity=None):  # noqa: ANN001
    try:
        return _orig_create_project(self, project, entity)
    except Exception:
        return None


_api_class.create_project = _tolerant_create_project


# Summary keys we try, in priority order, when extracting "best val acc" from
# a run. Different trainer versions have used different names; first hit wins.
_BEST_KEYS = (
    "summary/val_exact_accuracy",  # symmetric name (post 2026-04 trainers)
    "best_puzzle_acc",
    "val/puzzle_acc",
    "val/exact_accuracy",
    "val/cell_acc",
    "val/accuracy",
)
_ENERGY_KEYS = ("carbon/energy_kwh", "energy_kwh", "total_energy_consumed")
_CO2_KEYS = ("carbon/emissions_kg", "emissions_kg", "total_emissions")


def _first_match(summary: dict, keys: tuple[str, ...]) -> float | None:
    for k in keys:
        v = summary.get(k)
        if v is None:
            continue
        try:
            return float(v)
        except (TypeError, ValueError):
            continue
    return None


def _fmt(value, fmt="{:.4f}"):
    if value is None:
        return "—"
    try:
        return fmt.format(value)
    except (TypeError, ValueError):
        return str(value)


def _runs_to_rows(runs) -> list[dict]:
    rows: list[dict] = []
    for run in runs:
        summary = dict(run.summary or {})
        config = dict(run.config or {})
        rows.append({
            "id": run.id,
            "name": run.name,
            "state": run.state,
            "host": (config.get("host")
                     or summary.get("host")
                     or run.metadata.get("host", "?") if hasattr(run, "metadata") else "?"),
            "model_type": str(
                config.get("model", {}).get("model_type", "")
                if isinstance(config.get("model"), dict)
                else config.get("model_type", "")
            ),
            "seed": config.get("seed"),
            "best_val": _first_match(summary, _BEST_KEYS),
            "energy_kwh": _first_match(summary, _ENERGY_KEYS),
            "co2_kg": _first_match(summary, _CO2_KEYS),
            "runtime_min": (run.summary.get("_runtime", 0) or 0) / 60.0,
            "url": run.url,
            "created": str(run.created_at),
        })
    return rows


def _build_runs_table(rows: list[dict]) -> str:
    header = (
        "| Run | State | Seed | Best val | Energy (kWh) | CO₂ (kg) | Runtime (min) | URL |\n"
        "|---|---|---|---|---|---|---|---|"
    )
    lines = [header]
    for r in rows:
        lines.append(
            f"| `{r['name']}` ({r['id']}) | {r['state']} | {r.get('seed', '—')} | "
            f"{_fmt(r['best_val'])} | {_fmt(r['energy_kwh'], '{:.2f}')} | "
            f"{_fmt(r['co2_kg'], '{:.3f}')} | {_fmt(r['runtime_min'], '{:.0f}')} | "
            f"[link]({r['url']}) |"
        )
    return "\n".join(lines)


def _build_blocks(project: str, rows: list[dict]) -> list:
    headline = max(rows, key=lambda r: r["best_val"] or 0) if rows else None
    total_energy = sum(r["energy_kwh"] or 0 for r in rows)
    total_co2 = sum(r["co2_kg"] or 0 for r in rows)

    intro_md = (
        f"**Project:** `{project}` — **{len(rows)} runs** total. "
        f"Aggregate energy: **{total_energy:.2f} kWh**, "
        f"emissions: **{total_co2:.3f} kg CO₂eq**.\n\n"
        f"Auto-generated by `scripts/publish_runs_overview_report.py`. "
        f"Re-run any time to refresh."
    )
    if headline is not None and headline["best_val"] is not None:
        intro_md += (
            f"\n\n**Best so far:** `{headline['name']}` at "
            f"**{headline['best_val']:.4f}** val_puzzle_acc."
        )

    blocks: list = [
        wr.H1(text=f"TRM Runs Overview — {project}"),
        wr.MarkdownBlock(text=intro_md),
        wr.HorizontalRule(),
        wr.H2(text="All runs (sorted by best val)"),
        wr.MarkdownBlock(text=_build_runs_table(rows)),
        wr.HorizontalRule(),
        wr.H2(text="Per-run details"),
    ]

    for r in rows:
        details = (
            f"**State:** {r['state']}  ·  **Host:** {r['host']}  ·  "
            f"**Seed:** {r.get('seed', '—')}  ·  **Model:** `{r['model_type']}`  ·  "
            f"**Created:** {r['created']}\n\n"
            f"| Metric | Value |\n|---|---|\n"
            f"| best_val | {_fmt(r['best_val'])} |\n"
            f"| energy_kwh | {_fmt(r['energy_kwh'], '{:.3f}')} |\n"
            f"| co2_kg | {_fmt(r['co2_kg'], '{:.4f}')} |\n"
            f"| runtime_min | {_fmt(r['runtime_min'], '{:.0f}')} |\n\n"
            f"[Open in W&B]({r['url']})"
        )
        blocks.append(wr.H3(text=f"{r['name']}  (`{r['id']}`)"))
        blocks.append(wr.MarkdownBlock(text=details))

    return blocks


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--entity",
        default=os.getenv("TRM_WANDB_ENTITY") or "shamykyzer",
    )
    parser.add_argument(
        "--project",
        default=os.getenv("TRM_WANDB_PROJECT") or "TRM",
    )
    parser.add_argument(
        "--top-n", type=int, default=50,
        help="Limit the report to the top-N runs by best val acc",
    )
    parser.add_argument(
        "--title",
        default="TRM Runs Overview",
    )
    parser.add_argument(
        "--description",
        default=(
            "Auto-generated runs overview for the TRM project. Refreshes "
            "every time scripts/publish_runs_overview_report.py is invoked. "
            "Pairs with findings.md (narrative) and "
            "results/trm_runs_overview.csv (canonical CSV)."
        ),
    )
    args = parser.parse_args(argv)

    api = wandb.Api()
    print(f"[publish-runs] fetching runs from {args.entity}/{args.project} ...")
    runs = list(api.runs(f"{args.entity}/{args.project}"))
    print(f"[publish-runs] fetched {len(runs)} runs")
    rows = _runs_to_rows(runs)
    rows.sort(key=lambda r: (r["best_val"] is None, -(r["best_val"] or 0)))
    rows = rows[: args.top_n]
    print(f"[publish-runs] keeping top {len(rows)}")

    blocks = _build_blocks(args.project, rows)
    print(f"[publish-runs] built {len(blocks)} report blocks")

    report = wr.Report(
        entity=args.entity,
        project=args.project,
        title=args.title,
        description=args.description,
        blocks=blocks,
    )
    print(f"[publish-runs] saving to {args.entity}/{args.project} ...")
    report.save()

    print()
    print("REPORT PUBLISHED")
    print(f"URL:     {report.url}")
    print(f"Entity:  {args.entity}")
    print(f"Project: {args.project}")
    print(f"Runs:    {len(rows)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
